/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 05-Nov.-2023 09:35:29 				*/
/*  DBMS       : SQL Server 2008 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */
create database BDMantenedorPlato
go

use BDMantenedorPlato
go

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Insumo_Tipoinsumo]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Insumo] DROP CONSTRAINT [FK_Insumo_Tipoinsumo]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_InsumoPlato_Plato]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [InsumoPlato] DROP CONSTRAINT [FK_InsumoPlato_Plato]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_InsumoPlato_Insumo]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [InsumoPlato] DROP CONSTRAINT [FK_InsumoPlato_Insumo]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Plato_Tipoplato]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Plato] DROP CONSTRAINT [FK_Plato_Tipoplato]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Insumo]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Insumo]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[InsumoPlato]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [InsumoPlato]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Plato]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Plato]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Tipoinsumo]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Tipoinsumo]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Tipoplato]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Tipoplato]
GO

/* Create Tables */

CREATE TABLE [Insumo]
(
	[InsumoID] nvarchar(10) NOT NULL,
	[CantidadInsumo] int NOT NULL,
	[TipoinsumoID] nvarchar(10) NOT NULL,
	[EstadoInsumo] bit NOT NULL,
	[NombreInsumo] nvarchar(50) NOT NULL
)
GO

CREATE TABLE [InsumoPlato]
(
	[PlatoID] nvarchar(10) NULL,
	[InsumoID] nvarchar(10) NULL
)
GO

CREATE TABLE [Plato]
(
	[PlatoID] nvarchar(10) NOT NULL,
	[EstadoPlato] bit NULL,
	[TipoplatoID] nvarchar(10) NOT NULL,
	[NombrePlato] nvarchar(50) NULL,
	[PrecioPlato] decimal(10,2) NULL
)
GO

CREATE TABLE [Tipoinsumo]
(
	[NombreTipoInsumo] nvarchar(50) NULL,
	[TipoinsumoID] nvarchar(10) NOT NULL,
	[EstadoTipoInsumo] bit NULL
)
GO

CREATE TABLE [Tipoplato]
(
	[NombreTipoPlato] nvarchar(50) NULL,
	[TipoplatoID] nvarchar(10) NOT NULL,
	[EstadoTipoPlato] bit NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Insumo] 
 ADD CONSTRAINT [PK_Insumo]
	PRIMARY KEY CLUSTERED ([InsumoID] ASC)
GO

ALTER TABLE [Plato] 
 ADD CONSTRAINT [PK_Plato]
	PRIMARY KEY CLUSTERED ([PlatoID] ASC)
GO

ALTER TABLE [Tipoinsumo] 
 ADD CONSTRAINT [PK_Tipoinsumo]
	PRIMARY KEY CLUSTERED ([TipoinsumoID] ASC)
GO

ALTER TABLE [Tipoplato] 
 ADD CONSTRAINT [PK_Tipoplato]
	PRIMARY KEY CLUSTERED ([TipoplatoID] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [Insumo] ADD CONSTRAINT [FK_Insumo_Tipoinsumo]
	FOREIGN KEY ([TipoinsumoID]) REFERENCES [Tipoinsumo] ([TipoinsumoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [InsumoPlato] ADD CONSTRAINT [FK_InsumoPlato_Plato]
	FOREIGN KEY ([PlatoID]) REFERENCES [Plato] ([PlatoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [InsumoPlato] ADD CONSTRAINT [FK_InsumoPlato_Insumo]
	FOREIGN KEY ([InsumoID]) REFERENCES [Insumo] ([InsumoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Plato] ADD CONSTRAINT [FK_Plato_Tipoplato]
	FOREIGN KEY ([TipoplatoID]) REFERENCES [Tipoplato] ([TipoplatoID]) ON DELETE No Action ON UPDATE No Action
GO

-- PROCEDIMIENTOS ALMACENADOS
-- para TIPOPLATO

create or alter proc spInsertarTipoPlato
(@tipoplatoid nvarchar(10), @nombretipoplato nvarchar(50), @estadotipoplato bit)
as
insert into Tipoplato values
(@nombretipoplato, @tipoplatoid, @estadotipoplato)
go

create or alter proc spListarTipoPlato
as
select * from Tipoplato
where EstadoTipoPlato = 1
go

create or alter proc spEditarTipoPlato
(@tipoplatoid nvarchar(10), @nombretipoplato nvarchar(50), @estadotipoplato bit)
as
update
Tipoplato 
set
NombreTipoPlato = @nombretipoplato,
EstadoTipoPlato = @estadotipoplato
where 
@tipoplatoid = TipoplatoID
go

create or alter proc spDeshabilitarTipoPlato
(@tipoplatoid nvarchar(10))
as
update
Tipoplato
set
EstadoTipoPlato = 0
where
@tipoplatoid = TipoplatoID
go

select * from Tipoplato

-- para TIPOINSUMO

create or alter proc spInsertarTipoInsumo
(@tipoinsumoid nvarchar(10), @nombretipoinsumo nvarchar(50), @estadotipoinsumo bit)
as
insert into Tipoinsumo values
(@nombretipoinsumo, @tipoinsumoid, @estadotipoinsumo)
go

create or alter proc spListarTipoInsumo
as
select * from TipoInsumo
where EstadoTipoInsumo = 1
go

create or alter proc spEditarTipoInsumo
(@tipoinsumoid nvarchar(10), @nombretipoinsumo nvarchar(50), @estadotipoinsumo bit)
as
update
Tipoinsumo 
set
NombreTipoinsumo = @nombretipoinsumo,
EstadoTipoinsumo = @estadotipoinsumo
where 
@tipoinsumoid = tipoinsumoid
go

create or alter proc spDeshabilitarTipoinsumo
(@tipoinsumoid nvarchar(10))
as
update
Tipoinsumo
set
EstadoTipoinsumo = 0
where
@tipoinsumoid = TipoinsumoID
go

select * from Tipoinsumo

-- para INSUMO

create or alter proc spInsertarInsumo
(@insumoid nvarchar(10), @nombreinsumo nvarchar(50), @idtipoinsumo nvarchar(10), @cantidadinsumo int, @estadoinsumo bit)
as
insert into insumo values
(@insumoid, @cantidadinsumo, @idtipoinsumo, @estadoinsumo, @nombreinsumo)
go

create or alter proc spListarInsumo
as
select * from insumo
where EstadoInsumo = 1
go

create or alter proc spEditarInsumo
(@insumoid nvarchar(10), @nombreinsumo nvarchar(50), @idtipoinsumo nvarchar(10), @cantidadinsumo int, @estadoinsumo bit)
as
update
Insumo
set
NombreInsumo = @nombreinsumo,
TipoinsumoID = @idtipoinsumo,
CantidadInsumo = @cantidadinsumo,
Estadoinsumo = @estadoinsumo
where 
@insumoid = insumoid
go

create or alter proc spDeshabilitarinsumo
(@insumoid nvarchar(10))
as
update
insumo
set
Estadoinsumo = 0
where
@insumoid = insumoid
go

select * from insumo


-- para PLATO

create or alter proc spListarInsumoEscogido
(@insumoId nvarchar(10))
as
select * from Insumo
where InsumoID = @insumoid and EstadoInsumo = 1
go


create or alter proc spListarPlato
as
select * from Plato
where EstadoPlato = 1
go


create or alter proc spInsertarPlato
(@platoid nvarchar(50), @estadoplato bit, @tipoplatoid nvarchar(50), @nombreplato nvarchar(50), @precioplato decimal)
as
insert into Plato values
(@platoid, @estadoplato, @tipoplatoid, @nombreplato, @precioplato)
go

/*
alter table insumoplato
add EstadoInsumoPlato bit not null
*/

create or alter proc spListarInsumoPlato
(@idplato nvarchar(50))
as
select * from InsumoPlato
where estadoinsumoplato = 1 and @idplato = PlatoID
go

create or alter proc spInsertarInsumoPlato
(@insumoid nvarchar(50), @platoid nvarchar(50), @estadoinsumoplato bit)
as
if not exists (select 1 From InsumoPlato where @insumoid = InsumoID and @platoid = PlatoID)
begin
insert into InsumoPlato values
(@platoid, @insumoid, @estadoinsumoplato)
end
go

create or alter proc spEditarPlato
(@platoid nvarchar(50), @estadoplato bit, @tipoplatoid nvarchar(50), @nombreplato nvarchar(50), @precioplato decimal)
as
update Plato
set 
EstadoPlato = @estadoplato,
TipoplatoID = @tipoplatoid,
NombrePlato = @nombreplato,
PrecioPlato = @precioplato
where PlatoID = @platoid
go

create or alter proc spDeshabilitarInsumoPlato
(@insumoid nvarchar(10), @platoid nvarchar(10))
as
update InsumoPlato
set estadoinsumoplato = 0
where PlatoID = @platoid and InsumoID = @insumoid
go

create or alter proc spDeshabilitarPlato
(@platoid nvarchar(10))
as
update Plato
set EstadoPlato = 0
where PlatoID = @platoid
go

select * from insumoplato

select * from plato



/* DEFINIR PRIMARY KEY INSUMOPLATO
alter table insumoplato
add primary key (platoid, insumoid)

alter table insumoplato 
alter column insumoid nvarchar(10) not null


select * from insumoplato

delete from insumoplato
where PlatoID = 'hjh'
*/

select * from insumo


create or alter proc spListarDetallePlato
(@platoid nvarchar(10))
as
select * from Insumo i inner join InsumoPlato inpl on inpl.InsumoID = i.InsumoID
where inpl.PlatoID = @platoid and inpl.estadoinsumoplato = 1
go

SELECT * FROM INSUMOPLATO